# Created by Axel Rau <axel.rau@chaos1.de>
# $FreeBSD:$

PORTNAME=	idna
PORTVERSION=	2.0
CATEGORIES=	dns python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	axel.rau@chaos1.de
COMMENT=	Python IDNA2008 library (RFC 5891)

LICENSE=	BSD

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
