# Created by: Cullum Smith <cullum@c0ffee.net>

PORTNAME=	sqlparse02
PORTVERSION=	0.2.0
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	sqlparse-${DISTVERSION}

MAINTAINER=	cullum@c0ffee.net
COMMENT=	Non-validating SQL parser for Python (version 0.2.0)

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
USE_PYTHON=	autoplist concurrent distutils
USES=		python

.include <bsd.port.mk>
