# Created by: Axel Rau <axel.rau@chaos1.de>
# $FreeBSD: head/databases/py-sqlparse/Makefile 426458 2016-11-19 17:07:38Z sunpoet $

PORTNAME=	Automat
PORTVERSION=	0.5.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	axel.rau@chaos1.de
COMMENT=	

LICENSE=	MIT

NO_ARCH=	yes
USE_PYTHON=	autoplist distutils
USES=		python

.include <bsd.port.mk>
