# Created by: Axel Rau <axel.rau@chaos1.de>
# $FreeBSD: head/devel/py-attrs/Makefile 410763 2016-03-10 16:23:24Z rakuco $

PORTNAME=	attrs
PORTVERSION=	16.0.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	axel.rau@chaos1.de
COMMENT=	Python attributes without boilerplate

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
