# Created by: Axel Rau <axel.rau@chaos1.de>

PORTNAME=	attrs
PORTVERSION=	15.2.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	axel.rau@chaos1.de
COMMENT=	Python attributes without boilerplate

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=yes

.include <bsd.port.mk>
