# Created by: axel.rau@chaos1.de
# local variant of exim-4.84 with EXPERIMENTAL_TPDA turned on

PKGNAMESUFFIX=	-L484

COMMENT=	Local exim variant with EXPERIMENTAL_TPDA turned on

MASTERDIR=	${.CURDIR}/../exim

OPTIONS_SLAVE=	PGSQL WISHLIST

.include "${MASTERDIR}/Makefile"


